version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      ------------ Comment upon Tests
      - prometheus
      - grafana
      - seaweedfs
    environment:
      SESSION_KEY: "${SESSION_KEY}"
      REDIS_ADDR: "${REDIS_ADDR}" # example: redis:6379
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      SEAWEED_SERVER_ADDR: "${SEAWEED_SERVER_ADDR}"
      SEAWEED_UPLOAD_IP: "${SEAWEED_UPLOAD_IP}"
      GMAIL_EMAIL: "${GMAIL_EMAIL}"
      GMAIL_APP_PASSWORD: "${GMAIL_APP_PASSWORD}"
      ACCESS_SECRET: "${ACCESS_SECRET}"
    networks:
      - backend

  redis:
    image: 'redis:6.0-alpine'
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - backend

  seaweedfs:
    build:
      context: ./
      dockerfile: Dockerfile.weed
    ports:
      - "8080:8080"
      - "9333:9333"
    networks:
      - backend

  # ------------ Comment upon Tests
  prometheus:
    image: prom/prometheus:v2.24.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    restart: always
    networks:
      - backend

  # ------------ Comment upon Tests
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-store:/var/lib/grafana
    networks:
      - backend

# ------------ Comment upon Tests
volumes:
  grafana-store:
  prometheus_data:

networks:
  backend:
