global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: app
    metrics_path: /prometheus
    static_configs:
      - targets:
          -  app:8000 # docker-compose service name
  - job_name: redis_exporter
    static_configs:
      - targets:
          -  redis_exporter:9121 # docker-compose service name
  - job_name: minio_exporter
    static_configs:
      - targets:
          -  minio_exporter:9290 # docker-compose service name
